server.port: 8780

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/

# LOGGING
# Instead of logging the request in the handler explicitly, you could set
logging.level.com.spring.cloud.gateway: DEBUG
logging.level.org.springframework.cloud.gateway: DEBUG
logging.pattern.console: ${CONSOLE_LOG_PATTERN:-%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %4line %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}

# 关闭gateway
#spring.cloud.gateway.enabled: false

# Eureka Server中的服务名默认都是大写，该属性为true时，可以在路由配置中使用小写，例如：uri: lb://spring-cloud-microservice2
spring.cloud.gateway.discovery.locator.lower-case-service-id: true
# 开启服务发现，可从注册中心发现服务
spring.cloud.gateway.discovery.locator.enabled: true

spring:
  cloud:
    gateway:
      routes:
        # 以 /security 开头的调用认证微服务，例如 http://localhost:8780/security/auth/register，后面的 /auth/register 传递给认证微服务
        - id: security_route
          uri: lb://spring-cloud-security
          predicates:
            - Path=/security/**
          filters:
            - StripPrefix=1
        - id: microservice1_route
          uri: lb://spring-cloud-microservice1
          predicates:
            - Path=/microservice1/**
          # StripPrefix: 接受一个非负整数，对应的具体实现是StripPrefixGatewayFilterFactory，做用是去掉前缀，整数对应层数。
          # 在本例中访问的 /microservice1/echo/str，网关服务向后转发请求的时候会去掉 /microservice1，
          # microservice1 收到的请求是：/echo/str。
          filters:
            - StripPrefix=1
        - id: microservice2_route
          uri: lb://spring-cloud-microservice2
          predicates:
            - Path=/microservice2/**
          filters:
            - StripPrefix=1
      # CORS Configuration
      globalcors:
        corsConfigurations:
          '[/*/**]':
            # 允许所有网址的请求跨域
            allowedOrigins: "*"
            # 允许所有的请求跨域
            allowedMethods: "*"

management.endpoint.gateway.enabled: true # default value
management.endpoints.web.exposure.include: gateway
