spring.profiles.active: commons

spring.application.name: spring-cloud-microservice2
server.port: 8810

# LOGGING
logging.level.com.spring.cloud: DEBUG

## find Zipkin through service discovery
#spring.zipkin.baseUrl: https://spring-cloud-zipkin-server/
#spring.sleuth.sampler.probability: 1

# Ribbon load-balancer is now in maintenance mode, disabling Ribbon with Eureka Server and Client starters,
# using the Spring Cloud LoadBalancer
spring.cloud.loadbalancer.ribbon.enabled: false

# 发现客户端注册之后，Eureka默认认为是可用状态，不再检查发现客户端是否可用，开启发现客户端心跳检查，将发现客户端状态定时发送给Eureka
eureka.client.healthcheck.enabled: true

# change periodic heartbeat to the registry, default duration of 30 seconds
eureka.instance.leaseRenewalIntervalInSeconds: 10
