server.port: 9411
spring.application.name: spring-cloud-zipkin-server

# 添加下行配置解决异常
# java.lang.IllegalArgumentException: Prometheus requires that all meters with the same name have the same set of tag keys.
management.metrics.web.server.auto-time-requests: false
