spring.profiles.active: commons

spring.application.name: spring-cloud-microservice1
server.port: 8800

# LOGGING
logging.level.com.spring.cloud.microservice1: DEBUG

# find Zipkin through service discovery
spring.zipkin.baseUrl: https://spring-cloud-zipkin-server/
spring.sleuth.sampler.probability: 1
