server.port: 8781
spring.application.name: spring-cloud-stream-kafka

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/


# Kafka Streams Properties
spring.cloud.stream.kafka.streams.binder.brokers: localhost
spring.cloud.stream.kafka.streams.binder.serdeError: logAndFail
spring.cloud.stream.kafka.streams.binder.useNativeEncoding: false

# Kafka Streams producers Properties
spring.cloud.stream.kafka.streams.bindings.<binding name>.producer.useNativeEncoding: false

# Kafka Streams consumers Properties
spring.cloud.stream.kafka.streams.bindings.default.consumer.useNativeDecoding: false
spring.cloud.stream.kafka.streams.bindings.default.consumer.startOffset: latest

spring.cloud.stream.bindings.output.contentType: application/json
spring.cloud.stream.bindings.output.nativeEncoding: true

spring.cloud.stream.bindings.input.contentType: application/json
spring.cloud.stream.bindings.input.nativeDecoding: true






