#spring.profiles.active: commons

spring.application.name: spring-cloud-stream-rabbitmq-producer

# LOGGING
logging.level.com.spring.cloud: DEBUG

spring.rabbitmq.addresses: amqp://admin:admin@192.168.81.129:5672

spring.cloud.stream.bindings.input.destination: input-topic
