server.port: 8790
spring.application.name: spring-cloud-zuul

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/

# 对 /microservice1 的调用跳转到 SPRING-CLOUD-MICROSERVICE1 服务
zuul.routes.SPRING-CLOUD-MICROSERVICE1: /microservice1/**
zuul.routes.SPRING-CLOUD-MICROSERVICE2: /microservice2/**
zuul.routes.SPRING-CLOUD-MICROSERVICE3: /microservice3/**

# LOGGING
logging.level.com.spring.cloud.zuul: DEBUG
logging.level.org.spring.cloud.zuul: DEBUG
logging.pattern.console: ${CONSOLE_LOG_PATTERN:-%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %4line %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}
